# Import Dataset

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import metrics
wine= pd.read_table('wine.csv')
from sklearn import datasets
from sklearn import linear_model
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing

In [2]:
wine= pd.read_table('wine.csv', sep=',')
wine.head(10)

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      3    12.20        3.03  2.32               19.0         96   
1      1    13.30        1.72  2.14               17.0         94   
2      1    13.87        1.90  2.80               19.4        107   
3      1    13.39        1.77  2.62               16.1         93   
4      2    11.65        1.67  2.62               26.0         88   
5      2    12.70        3.87  2.40               23.0        101   
6      1    13.88        1.89  2.59               15.0        101   
7      3    12.45        3.03  2.64               27.0         97   
8      3    14.16        2.51  2.48               20.0         91   
9      1    14.02        1.68  2.21               16.0         96   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           1.25        0.49                  0.40             0.73   
1           2.40        2.19                  0.27             1.35   
2           2.95        2.97                  0.37             1.76   
3           2.85        2.94                  0.34             1.45   
4           1.92        1.61                  0.40             1.34   
5           2.83        2.55                  0.43             1.95   
6           3.25        3.56                  0.17             1.70   
7           1.90        0.58                  0.63             1.14   
8           1.68        0.70                  0.44             1.24   
9           2.65        2.33                  0.26             1.98   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.50  0.66                          1.83      510  
1             3.95  1.02                          2.77     1285  
2             4.50  1.25                          3.40      915  
3             4.80  0.92                          3.22     1195  
4             2.60  1.36                          3.21      562  
5             2.57  1.19                          3.13      463  
6             5.43  0.88                          3.56     1095  
7             7.50  0.67                          1.73      880  
8             9.70  0.62                          1.71      660  
9             4.70  1.04                          3.59     1035

In [3]:
X_scaled = preprocessing.scale(wine)

In [4]:
X_scaled

array([[ 1.22474487, -1.19526291,  0.60582574, ..., -1.25426748,
        -0.93782812, -0.83711381],
       [-1.22474487,  0.26787191, -0.5688373 , ...,  0.27183744,
         0.32756676,  1.74410082],
       [-1.22474487,  1.02604177, -0.40743322, ...,  1.24684892,
         1.17565057,  0.511779  ],
       ...,
       [ 0.        , -1.51449233, -1.13375159, ...,  0.14466203,
         0.81218608,  0.41519161],
       [ 0.        , -1.18196169, -1.04408265, ...,  1.37402433,
         0.73141619, -0.14434911],
       [-1.22474487,  1.33196996, -0.17429399, ...,  1.24684892,
         0.86603267,  2.49348571]])

In [5]:
wine.shape

(144, 14)

In [6]:
wine.columns

Index(['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash',
       'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid phenols',
       'Proanthocyanins', 'Color intensity', 'Hue',
       'OD280/OD315 of diluted wines', 'Proline'],
      dtype='object')

In [7]:
wine.dtypes


Class                             int64
Alcohol                         float64
Malic acid                      float64
Ash                             float64
Alcalinity of ash               float64
Magnesium                         int64
Total phenols                   float64
Flavanoids                      float64
Nonflavanoid phenols            float64
Proanthocyanins                 float64
Color intensity                 float64
Hue                             float64
OD280/OD315 of diluted wines    float64
Proline                           int64
dtype: object

In [8]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for col in wine.columns:
    wine[col] = labelencoder.fit_transform(wine[col])
 
wine.head()

Class  Alcohol  Malic acid  Ash  Alcalinity of ash  Magnesium  \
0      2       12          78   30                 29         16   
1      0       56          39   13                 18         14   
2      0       85          51   64                 31         27   
3      0       60          42   55                 13         13   
4      1        2          36   55                 51          8   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0              3           3                    21                6   
1             48          60                    10               33   
2             67          87                    19               57   
3             65          86                    17               42   
4             34          46                    21               32   

   Color intensity  Hue  OD280/OD315 of diluted wines  Proline  
0               69   12                            27       21  
1               38   43                            59       86  
2               50   63                            86       66  
3               54   35                            80       83  
4               10   68                            79       27

In [9]:
wine['Alcohol'].unique()

array([ 12,  56,  85,  60,   2,  30,  86,  21,  93,  88,  83,  19,  82,
         9,  64,  10, 105,  61,  57,  26,  78,  32,  23,  55,  84,  59,
        69,  33,  16,  81,  98,  54, 104,  80,  72,  45,  27,  42,  44,
        34,   8,   6,  68,  49,  94,  46,  20,  91,  92, 100,  77,  28,
        99,  15,  51,  63, 103,  37, 102,  66,  24,  95,  11,  48,  97,
        67,  47,  22,  40,  25,  41,  43,  65,  14,  18,  58,   1,   0,
        89,  71,  52,  76,  39,  70,  50,  96,  31,  87, 101,  79,  73,
        53,  36,   3,  75,   5,  74,  17,  62,  29,   4,  35,  38,   7,
        13,  90], dtype=int64)

In [10]:
print(wine.groupby('Class').size())

Class
0    48
1    48
2    48
dtype: int64


# Train/Test Split Data (80:20)

In [11]:
train_wine = wine.iloc[:round(len(wine)*.8)]
test_wine = wine.iloc[round(len(wine)*.2)+1:]

In [12]:
# Divide each into x and y
x_train = train_wine.loc[:, train_wine.columns != 'Class']
y_train = train_wine.Class

x_test = test_wine.loc[:, test_wine.columns != 'Class']
y_test = test_wine.Class

# Decision Tree

In [13]:
from sklearn import tree

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
x_test

Alcohol  Malic acid  Ash  Alcalinity of ash  Magnesium  Total phenols  \
30        98          38   39                 11         43             63   
31        54         105   24                 34         37             17   
32       104          40   35                  2         11             71   
33        80          27   60                 32         45             67   
34        72          45   60                 19         31             65   
35        23          14   23                 20          5             38   
36        45          95   30                 42          5             21   
37        27          20   10                 17         20             39   
38        16           9   26                 12         21             40   
39        42          87   31                 25         26              8   
40        44           1    2                 12          6             36   
41         9          10   45                 47          1             38   
42        34          61   36                 47         18              2   
43         8           2    9                 29          6             50   
44         6          75   21                 23         31             24   
45        68          81   61                 45         17             16   
46        49          62   58                 26         21             63   
47        94          29   43                 15         28             75   
48        46          24   11                 10         18             48   
49        20          67   25                 41         10             22   
50        91          23   30                 17         15             43   
51        92         103   62                 48         16             40   
52        19           7   11                 25          8             78   
53       100          37   60                 49         18             63   
54        77         114   41                 36         15             22   
55        28           4   22                 23         19             43   
56        61          99   43                 44         22             28   
57        99          52   61                 34         37             63   
58        15          81   19                 23          8             65   
59        51          43   13                  1         20             61   
..       ...         ...  ...                ...        ...            ...   
114       37          84   51                 41         26             21   
115       70          35   32                 30         26             66   
116        3          49    6                 12         17             19   
117       75          46   32                 19         24             50   
118       14          97   18                 25         31              7   
119       66          80   55                 47         40              9   
120       50          70   33                 34         37             21   
121        5          39    4                 32          6             53   
122       86         111   21                 34          2              0   
123       19          13   50                 24         18             50   
124       19          10   15                 29          7             77   
125       65          35   22                 47          7             31   
126       53         100   27                 20         23             60   
127       74          15    6                 23         14             41   
128        9          17   28                 46          0             43   
129       17          64   42                 38         18             56   
130       62          94   12                 27         10             51   
131       29          27   24                 37          2              7   
132       15          31   19                 35         23              1   
133        4          58   

In [16]:
y_test

30     0
31     2
32     0
33     0
34     0
35     2
36     1
37     1
38     1
39     2
40     1
41     1
42     2
43     1
44     1
45     2
46     0
47     0
48     0
49     1
50     0
51     2
52     1
53     2
54     2
55     1
56     2
57     0
58     1
59     0
      ..
114    2
115    0
116    1
117    0
118    2
119    2
120    2
121    1
122    2
123    1
124    1
125    1
126    0
127    1
128    1
129    1
130    0
131    1
132    1
133    1
134    1
135    2
136    2
137    1
138    1
139    0
140    2
141    1
142    1
143    0
Name: Class, Length: 114, dtype: int64

In [17]:
data = x_train
target = y_train

In [18]:
clf = tree.DecisionTreeClassifier()
# Train Data
clf_train = clf.fit(data, target)

In [19]:
# get predictions
prd_clf = clf.predict(x_test)

In [20]:
print (metrics.accuracy_score(y_test,prd_clf))

0.9736842105263158


In [21]:
# Summerize the fit of the model
print(metrics.classification_report(y_test,prd_clf))

             precision    recall  f1-score   support

          0       0.97      0.97      0.97        37
          1       0.95      0.97      0.96        40
          2       1.00      0.97      0.99        37

avg / total       0.97      0.97      0.97       114



In [22]:
confusion_matrix(y_test, prd_clf)

array([[36,  1,  0],
       [ 1, 39,  0],
       [ 0,  1, 36]], dtype=int64)

# Random Forest

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
rfc = RandomForestClassifier(n_estimators=10)

In [25]:
# Train Data
rfc = rfc.fit(data, target)

In [26]:
# get predictions
prd_rfc = rfc.predict(x_test)

In [27]:
print (metrics.accuracy_score(y_test,prd_rfc))

0.9912280701754386


In [28]:
# Summerize the fit of the model
print(metrics.classification_report(y_test,prd_rfc))

             precision    recall  f1-score   support

          0       0.97      1.00      0.99        37
          1       1.00      0.97      0.99        40
          2       1.00      1.00      1.00        37

avg / total       0.99      0.99      0.99       114



In [29]:
confusion_matrix(y_test, prd_rfc)

array([[37,  0,  0],
       [ 1, 39,  0],
       [ 0,  0, 37]], dtype=int64)

# Logistic Regression

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
lr = LogisticRegression()

In [32]:
# Train Data
lr.fit(data, target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
# get predictions
prd_lr = lr.predict(x_test)

In [34]:
print(metrics.accuracy_score(y_test,prd_lr))

0.9649122807017544


In [35]:
# Summerize the fit of the model
print(metrics.classification_report(y_test, prd_lr))

             precision    recall  f1-score   support

          0       0.90      1.00      0.95        37
          1       1.00      0.93      0.96        40
          2       1.00      0.97      0.99        37

avg / total       0.97      0.96      0.97       114



In [36]:
confusion_matrix(y_test, prd_lr)

array([[37,  0,  0],
       [ 3, 37,  0],
       [ 1,  0, 36]], dtype=int64)

# K-Nearest Neighbour

In [37]:
from sklearn.neighbors import KNeighborsClassifier
nb = KNeighborsClassifier(n_neighbors=3)
nb.fit(data, target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [38]:
# get predictions
prd_nb = nb.predict(x_test)

In [39]:
print(metrics.accuracy_score(y_test, prd_nb))

0.9649122807017544


In [40]:
print(metrics.classification_report(y_test, prd_nb))

             precision    recall  f1-score   support

          0       0.95      1.00      0.97        37
          1       1.00      0.90      0.95        40
          2       0.95      1.00      0.97        37

avg / total       0.97      0.96      0.96       114



In [41]:
confusion_matrix(y_test, prd_nb)

array([[37,  0,  0],
       [ 2, 36,  2],
       [ 0,  0, 37]], dtype=int64)