# Import Dataset

In [235]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import metrics
wine= pd.read_table('wine.csv')
from sklearn import datasets
from sklearn import linear_model
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing

In [236]:
wine= pd.read_table('wine.csv', sep=',')
wine.head(10)

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      3    12.20        3.03  2.32               19.0         96   
1      1    13.30        1.72  2.14               17.0         94   
2      1    13.87        1.90  2.80               19.4        107   
3      1    13.39        1.77  2.62               16.1         93   
4      2    11.65        1.67  2.62               26.0         88   
5      2    12.70        3.87  2.40               23.0        101   
6      1    13.88        1.89  2.59               15.0        101   
7      3    12.45        3.03  2.64               27.0         97   
8      3    14.16        2.51  2.48               20.0         91   
9      1    14.02        1.68  2.21               16.0         96   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           1.25        0.49                  0.40             0.73   
1           2.40        2.19                  0.27             1.35   
2           2.95        2.97                  0.37             1.76   
3           2.85        2.94                  0.34             1.45   
4           1.92        1.61                  0.40             1.34   
5           2.83        2.55                  0.43             1.95   
6           3.25        3.56                  0.17             1.70   
7           1.90        0.58                  0.63             1.14   
8           1.68        0.70                  0.44             1.24   
9           2.65        2.33                  0.26             1.98   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.50  0.66                          1.83      510  
1             3.95  1.02                          2.77     1285  
2             4.50  1.25                          3.40      915  
3             4.80  0.92                          3.22     1195  
4             2.60  1.36                          3.21      562  
5             2.57  1.19                          3.13      463  
6             5.43  0.88                          3.56     1095  
7             7.50  0.67                          1.73      880  
8             9.70  0.62                          1.71      660  
9             4.70  1.04                          3.59     1035

In [237]:
X_scaled = preprocessing.scale(wine)

In [238]:
X_scaled

array([[ 1.22474487, -1.19526291,  0.60582574, ..., -1.25426748,
        -0.93782812, -0.83711381],
       [-1.22474487,  0.26787191, -0.5688373 , ...,  0.27183744,
         0.32756676,  1.74410082],
       [-1.22474487,  1.02604177, -0.40743322, ...,  1.24684892,
         1.17565057,  0.511779  ],
       ...,
       [ 0.        , -1.51449233, -1.13375159, ...,  0.14466203,
         0.81218608,  0.41519161],
       [ 0.        , -1.18196169, -1.04408265, ...,  1.37402433,
         0.73141619, -0.14434911],
       [-1.22474487,  1.33196996, -0.17429399, ...,  1.24684892,
         0.86603267,  2.49348571]])

In [239]:
wine.shape

(144, 14)

In [240]:
wine.columns

Index(['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash',
       'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid phenols',
       'Proanthocyanins', 'Color intensity', 'Hue',
       'OD280/OD315 of diluted wines', 'Proline'],
      dtype='object')

In [241]:
wine.dtypes

Class                             int64
Alcohol                         float64
Malic acid                      float64
Ash                             float64
Alcalinity of ash               float64
Magnesium                         int64
Total phenols                   float64
Flavanoids                      float64
Nonflavanoid phenols            float64
Proanthocyanins                 float64
Color intensity                 float64
Hue                             float64
OD280/OD315 of diluted wines    float64
Proline                           int64
dtype: object

In [242]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for col in wine.columns:
    wine[col] = labelencoder.fit_transform(wine[col])
 
wine.head()

Class  Alcohol  Malic acid  Ash  Alcalinity of ash  Magnesium  \
0      2       12          78   30                 29         16   
1      0       56          39   13                 18         14   
2      0       85          51   64                 31         27   
3      0       60          42   55                 13         13   
4      1        2          36   55                 51          8   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0              3           3                    21                6   
1             48          60                    10               33   
2             67          87                    19               57   
3             65          86                    17               42   
4             34          46                    21               32   

   Color intensity  Hue  OD280/OD315 of diluted wines  Proline  
0               69   12                            27       21  
1               38   43                            59       86  
2               50   63                            86       66  
3               54   35                            80       83  
4               10   68                            79       27

In [243]:
wine['Alcohol'].unique()

array([ 12,  56,  85,  60,   2,  30,  86,  21,  93,  88,  83,  19,  82,
         9,  64,  10, 105,  61,  57,  26,  78,  32,  23,  55,  84,  59,
        69,  33,  16,  81,  98,  54, 104,  80,  72,  45,  27,  42,  44,
        34,   8,   6,  68,  49,  94,  46,  20,  91,  92, 100,  77,  28,
        99,  15,  51,  63, 103,  37, 102,  66,  24,  95,  11,  48,  97,
        67,  47,  22,  40,  25,  41,  43,  65,  14,  18,  58,   1,   0,
        89,  71,  52,  76,  39,  70,  50,  96,  31,  87, 101,  79,  73,
        53,  36,   3,  75,   5,  74,  17,  62,  29,   4,  35,  38,   7,
        13,  90], dtype=int64)

In [244]:
print(wine.groupby('Class').size())

Class
0    48
1    48
2    48
dtype: int64


# Train/Test Split Data (90:10)

In [245]:
train_wine = wine.iloc[:round(len(wine)*.9)]
test_wine = wine.iloc[round(len(wine)*.1)+1:]

In [246]:
# Divide each into x and y
x_train = train_wine.loc[:, train_wine.columns != 'Class']
y_train = train_wine.Class

x_test = test_wine.loc[:, test_wine.columns != 'Class']
y_test = test_wine.Class

# Decision Tree

In [247]:
from sklearn import tree

In [248]:
from sklearn.tree import DecisionTreeClassifier

In [249]:
data = x_train
target = y_train

In [250]:
clf = tree.DecisionTreeClassifier()
# Train Data
clf_train = clf.fit(data, target)

In [251]:
# get predictions
prd_clf = clf.predict(x_test)

In [252]:
print (metrics.accuracy_score(y_test,prd_clf))

0.9844961240310077


In [253]:
# Summerize the fit of the model
print(metrics.classification_report(y_test,prd_clf))

             precision    recall  f1-score   support

          0       0.95      1.00      0.98        42
          1       1.00      0.95      0.98        44
          2       1.00      1.00      1.00        43

avg / total       0.99      0.98      0.98       129



In [254]:
confusion_matrix(y_test, prd_clf)

array([[42,  0,  0],
       [ 2, 42,  0],
       [ 0,  0, 43]], dtype=int64)

# Random Forest

In [255]:
from sklearn.ensemble import RandomForestClassifier

In [256]:
rfc = RandomForestClassifier(n_estimators=10)

In [257]:
# Train Data
rfc = rfc.fit(data, target)

In [258]:
# get predictions
prd_rfc = rfc.predict(x_test)

In [259]:
print (metrics.accuracy_score(y_test,prd_rfc))

0.9922480620155039


In [260]:
# Summerize the fit of the model
print(metrics.classification_report(y_test,prd_rfc))

             precision    recall  f1-score   support

          0       0.98      1.00      0.99        42
          1       1.00      0.98      0.99        44
          2       1.00      1.00      1.00        43

avg / total       0.99      0.99      0.99       129



In [261]:
confusion_matrix(y_test, prd_rfc)

array([[42,  0,  0],
       [ 1, 43,  0],
       [ 0,  0, 43]], dtype=int64)

# Logistic Regression

In [262]:
from sklearn.linear_model import LogisticRegression

In [263]:
lr = LogisticRegression()

In [264]:
# Train Data
lr.fit(data, target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [265]:
# get predictions
prd_lr = lr.predict(x_test)

In [266]:
print(metrics.accuracy_score(y_test,prd_lr))

0.9767441860465116


In [267]:
# Summerize the fit of the model
print(metrics.classification_report(y_test, prd_lr))

             precision    recall  f1-score   support

          0       0.93      1.00      0.97        42
          1       1.00      0.93      0.96        44
          2       1.00      1.00      1.00        43

avg / total       0.98      0.98      0.98       129



In [268]:
# Summerize the fit of the model
print(metrics.classification_report(y_test, prd_lr))

             precision    recall  f1-score   support

          0       0.93      1.00      0.97        42
          1       1.00      0.93      0.96        44
          2       1.00      1.00      1.00        43

avg / total       0.98      0.98      0.98       129



# K-Nearest Neighbour

In [269]:
from sklearn.neighbors import KNeighborsClassifier
nb = KNeighborsClassifier(n_neighbors=3)
nb.fit(data, target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [270]:
# get predictions
prd_nb = nb.predict(x_test)

In [271]:
print(metrics.accuracy_score(y_test, prd_nb))

0.9689922480620154


In [272]:
print(metrics.classification_report(y_test, prd_nb))

             precision    recall  f1-score   support

          0       0.95      1.00      0.98        42
          1       1.00      0.91      0.95        44
          2       0.96      1.00      0.98        43

avg / total       0.97      0.97      0.97       129



In [273]:
confusion_matrix(y_test, prd_nb)

array([[42,  0,  0],
       [ 2, 40,  2],
       [ 0,  0, 43]], dtype=int64)